### get user info
GET http://localhost:8080/api/user/info
Content-Type: application/json;charset=utf-8
Access-Token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJoZWxsb193b3JsZCIsImV4cCI6MTYyODkxMDcxMX0.S8dvOIPuy9gwZnGh31ChAF-vMi9KvzH43iRHdj6h2Cyb6lexBQ-ZxG5LWyMtLxL8nZo1z49g9_Y89xquj-rRYg

### user login
POST http://localhost:8080/api/auth/login
Content-Type: application/json;charset=utf-8

{
  "username": "hello_world",
  "password": "123456"
}

### user logout
DELETE http://localhost:8080/auth/logout
Access-Token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyZjU2ZjE5ODVlYWE0NmI2ODk2OGRiMjE3NWU0ZmI4MiIsImV4cCI6MTYxODQ3NTI4NX0.Gmai0b1lBLDq6XCjneMz2cLhDoqOIPxBnz1wnyJOZz1AWzlabxv_9dIVpXuz1yxXgRQsuDw2Df4ElBRq2xZf9Q
