spring:
  application:
    name: bulk
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/bulk?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: xiaoyu
    hikari:
      connection-timeout: 60000
      idle-timeout: 30000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    host: 192.168.1.29
    port: 6379
    password: 123456
  cache:
    type: redis
mybatis:
  type-aliases-package: cool.likeu.bulk.repo.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: off
    lazy-loading-enabled: on
    aggressive-lazy-loading: off
logging:
  level:
    cool.likeu.bulk: debug
    com.baomidou.mybatisplus: debug
    org.springframework.security: debug
